# ==========================================
# CONFIGURACIÓN DE CONEXIÓN - NEON TECH (APPGASTOS-MATIAS)
# ==========================================

# CONFIGURACIÓN JWT
# Puedes poner la clave que quieras, pero debe ser larga para ser segura
app.jwt.secret=EstaEsUnaClaveSecretaMuyLargaParaQueElAlgoritmoHS512NoFalle123456
app.jwt.expirationMs=86400000

# URL de conexión (He agregado jdbc: al principio y mantenido el pooler para eficiencia)
spring.datasource.url=jdbc:postgresql://ep-snowy-river-aqx7ueue-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require

# Credenciales
spring.datasource.username=neondb_owner
# REEMPLAZA npg_7ux... POR TU NUEVA CONTRASEÑA AQUÍ:
spring.datasource.password=npg_7uxMDQkK3lJW
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
# 'update' creará las tablas (User, Expense, Category, Budget) automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración extra para Neon (evita cierres de conexión inesperados)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# DESACTIVAR H2 (Ya no lo necesitamos)
spring.h2.console.enabled=false
